;;(defvar xdg-home (concat (getenv "XDG_CONFIG_HOME") "/emacs/"))
(defvar xdg-home "~/.emacs.d/dotemacs/")

(add-to-list 'auto-coding-alist '("\\.editorconfig\\'" . utf-8))

;; ;;(load-file (concat xdg-home "/.gashu/el-get.el"))
(load-file (concat xdg-home ".gashu/elpaca.el"))
(load-file (concat xdg-home ".gashu/general.el"))
(load-file (concat xdg-home ".gashu/evil.el"))
(load-file (concat xdg-home ".gashu/vertico.el"))
(load-file (concat xdg-home ".gashu/corfu.el"))
(load-file (concat xdg-home ".gashu/ui.el"))
(load-file (concat xdg-home ".gashu/config.el"))
(load-file (concat xdg-home ".gashu/yasnippet.el"))
(use-package async :ensure t)
(use-package popup :ensure t)
;;(load-file (concat xdg-home ".gashu/straight.el"))
;;(load-file (concat xdg-home ".gashu/auto-update-config.el"))
;;(load-file (concat xdg-home ".gashu/setup-load-path.el"))
;;(when (string= system-type "gnu/linux")
;;	(load-file (concat xdg-home ".gashu/lsp-bridge.el")))
(load-file (concat xdg-home ".gashu/lsp.el"))
(load-file (concat xdg-home ".gashu/tree-sit.el"))
(load-file (concat xdg-home ".gashu/lisp.el"))
;; ;; ;;(load-file "~/.gashu/eglot.el")
;; ;;(when (string= system-type "gnu/linux")
;; 	;;(load-file (concat xdg-home ".gashu/lspce.el")))
(load-file (concat xdg-home ".gashu/magit.el"))
(load-file (concat xdg-home ".gashu/which-key.el"))
(load-file (concat xdg-home ".gashu/ag.el"))
(load-file (concat xdg-home ".gashu/flycheck.el"))
;; ;;(use-package hydra)
(load-file (concat xdg-home ".gashu/winum.el"))
;;(load-file (concat xdg-home ".gashu/pdf.el"))
(load-file (concat xdg-home ".gashu/undo.el"))
(load-file (concat xdg-home ".gashu/editorconfig.el"))
(load-file (concat xdg-home ".gashu/helpful.el"))
;;(load-file (concat xdg-home ".gashu/avy.el"))
(load-file (concat xdg-home ".gashu/search-config.el"))
;;(load-file (concat xdg-home ".gashu/additional-hooks.el"))
(load-file (concat xdg-home ".gashu/bookmark+.el"))
;;(load-file (concat xdg-home ".gashu/bm.el"))
;; ;;(load-file (concat xdg-home "/.gashu/dired+.el"))
(load-file (concat xdg-home ".gashu/dired-stuff.el"))
(load-file (concat xdg-home ".gashu/projectile.el"))
(load-file (concat xdg-home ".gashu/tempel.el"))
;;(load-file (concat xdg-home ".gashu/company.el"))
(when (string= system-type "gnu/linux")
	(load-file (concat xdg-home ".gashu/debug.el")))
;;; (load-file (concat xdg-home ".gashu/flutter.el"))
;;;(load-file (concat xdg-home ".gashu/omnisharp.el"))
(load-file (concat xdg-home ".gashu/csharp.el"))
;;; (load-file (concat xdg-home ".gashu/rust.el"))
;;;(load-file (concat xdg-home ".gashu/web.el"))
;;(load-file (concat xdg-home ".gashu/smerge.el"))
;;(load-file (concat xdg-home ".gashu/php.el"))
;;(load-file (concat xdg-home ".gashu/lsp-bridge-hooks.el"))
(load-file (concat xdg-home ".gashu/javascript.el"))
;;(load-file (concat xdg-home ".gashu/react.el"))
;;(load-file (concat xdg-home ".gashu/clojure.el"))
;;(load-file (concat xdg-home ".gashu/schala.el"))
(load-file (concat xdg-home ".gashu/cpp.el"))
(when (string= system-type "gnu/linux")
	(load-file (concat xdg-home ".gashu/zig.el")))
;;(when (string= system-type "gnu/linux")
;;	(load-file (concat xdg-home ".gashu/java.el")))
;;(load-file (concat xdg-home ".gashu/lilypond.el"))
;; (load-file (concat xdg-home ".gashu/hydra-keys.el"))
;; (load-file (concat xdg-home ".gashu/slime.el"))
(load-file (concat xdg-home ".gashu/sly.el"))
;; (load-file (concat xdg-home ".gashu/eaf.el"))
;; (load-file (concat xdg-home ".gashu/citre.el"))
;;(when (string= system-type "gnu/linux")
(load-file (concat xdg-home ".gashu/vterm.el"))
(load-file (concat xdg-home ".gashu/ibuffer.el"))
(load-file (concat xdg-home ".gashu/workspaces.el"))
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
	 '("1b7e575c6681e66d8d83634c2c160b40af12f3756360a4dd81b8032f4495cb5e"
		 default))
 '(package-selected-packages nil)
 '(safe-local-variable-values
	 '((Package . CL-PPCRE) (Base . 10) (Package . CL-USER)
		 (Syntax . COMMON-LISP))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
